# Generated by Django 5.0.7 on 2024-07-30 03:20

from django.db import migrations


def create_permissions(apps, schema_editor):
    UserPermission = apps.get_model('user', 'UserPermission')

    permissions = [
        ('SUPERADMIN', 'Super Admin'),
        ('ADMIN', 'Admin'),
        ('PERMISSION1', 'Permission 1'),
        ('PERMISSION2', 'Permission 2'),
    ]

    new_permissions = []
    for codename, name in permissions:
        new_permissions.append(UserPermission(codename=codename, name=name))
    UserPermission.objects.bulk_create(new_permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_permissions),
    ]
