# Generated by Django 5.0.7 on 2024-07-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240730_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
